In [10]:
import numpy as np

# Create an array from a list
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [11]:
# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Create an array of zeros
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [13]:
# Create an array of ones
ones = np.ones(3)
ones

array([1., 1., 1.])

In [14]:
# Create a range of values
range_arr = np.arange(0, 10, 2)  # Creates [0, 2, 4, 6, 8]
range_arr

array([0, 2, 4, 6, 8])

In [15]:
# Get the shape of an array
shape = arr.shape  # Returns (5,) for a 1D array
shape

(5,)

In [17]:
# Reshape an array
reshaped = arr.reshape(5, 1)
reshaped

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
# Get the number of dimensions
dimensions = matrix.ndim  # Returns 2 for a 2D array
dimensions

2

In [20]:
# Element-wise addition
result_add = arr + 2
result_add

array([3, 4, 5, 6, 7])

In [21]:
# Element-wise multiplication
result_mul = arr * 3
result_mul

array([ 3,  6,  9, 12, 15])

In [22]:
# Dot product of two arrays
dot_product = np.dot(arr, [2, 2, 2, 2, 2])
dot_product

30

In [23]:
# Element-wise square root
sqrt_arr = np.sqrt(arr)
sqrt_arr

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [24]:
# Access elements by index
element = arr[2]  # Returns the third element (3)
element

3

In [25]:
# Slice an array
slice = arr[1:4]  # Returns [2, 3, 4]
slice

array([2, 3, 4])

In [27]:
# Calculate mean, median, and standard deviation
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
print(mean)
print(median)
print(std_dev)

3.0
3.0
1.4142135623730951


In [28]:
# Concatenate arrays horizontally
concat_horizontal = np.concatenate((arr, arr))
concat_horizontal

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [29]:
# Stack arrays vertically
stack_vertical = np.vstack((matrix, matrix))
stack_vertical

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# Boolean indexing
greater_than_3 = arr[arr > 3]
greater_than_3

array([4, 5])

In [31]:
# Sum along a specified axis
sum_axis0 = np.sum(matrix, axis=0)  # Sum of columns
sum_axis1 = np.sum(matrix, axis=1)  # Sum of rows
print(sum_axis0)
print(sum_axis1)


[12 15 18]
[ 6 15 24]
