In [1]:
import numpy as np

# Create a 1D array (vector) from a list
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)

1D Array:
[1 2 3 4 5]


In [2]:
# Create a 2D array (matrix) from a list of lists
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(arr2d)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Create an array of zeros
zeros = np.zeros(5)
print("\nArray of Zeros:")
print(zeros)


Array of Zeros:
[0. 0. 0. 0. 0.]


In [4]:
# Create an array of ones
ones = np.ones(3)
print("\nArray of Ones:")
print(ones)


Array of Ones:
[1. 1. 1.]


In [5]:
# Create an identity matrix (square matrix with diagonal of 1s)
identity = np.eye(3)
print("\nIdentity Matrix:")
print(identity)


Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# Create an array with a range of values
range_arr = np.arange(0, 10, 2)  # Creates [0, 2, 4, 6, 8]
print("\nArray with a Range of Values:")
print(range_arr)


Array with a Range of Values:
[0 2 4 6 8]
