In [3]:
# Matrix multiplication
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)  # or result = A @ B
result

array([[19, 22],
       [43, 50]])

In [5]:
# matrix transposition

A = np.array([[1, 2], [3, 4]])

transposed = A.T  # or transposed = np.transpose(A)
transposed

array([[1, 3],
       [2, 4]])

In [6]:
# Matrix inversion

A = np.array([[1, 2], [3, 4]])

inverse_A = np.linalg.inv(A)
inverse_A

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
# eigenvalues and eigenvectors

A = np.array([[1, 2], [2, 4]])

eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues, eigenvectors

(array([0., 5.]),
 array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))

In [8]:
#Solving Linear Systems


A = np.array([[2, 1], [1, 3]])
b = np.array([5, 8])

x = np.linalg.solve(A, b)
x

array([1.4, 2.2])

In [9]:
# matrix determinant

A = np.array([[3, 1], [2, 2]])

determinant = np.linalg.det(A)
determinant

4.000000000000001

In [10]:
#Matrix Trace

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

trace = np.trace(A)
trace

15

In [11]:
# matrix rank

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

rank = np.linalg.matrix_rank(A)
rank

2

In [13]:
# singular value decomposition
A = np.array([[1, 2], [2, 3], [3, 4]])

U, S, V = np.linalg.svd(A)
U
S
V

array([[-0.56959484, -0.82192562],
       [-0.82192562,  0.56959484]])

In [15]:
# matrix exponentiation
from scipy.linalg import expm

A = np.array([[1, 2], [0, 1]])

exp_matrix = expm(A)
exp_matrix

array([[2.71828183, 5.43656366],
       [0.        , 2.71828183]])