In [1]:
import numpy as np

# Generate 10 random values between 0 and 1
random_values = np.random.uniform(0, 1, 10)
random_values

array([0.20353406, 0.83811857, 0.30850971, 0.59134173, 0.99422676,
       0.52345299, 0.7306809 , 0.41271661, 0.46272586, 0.06472556])

In [2]:

# Generate 10 random values from a normal distribution with mean 0 and std 1
random_values = np.random.normal(0, 1, 10)
random_values

array([-1.00111066, -0.64193095,  0.22161134, -1.5723769 ,  0.49681913,
       -0.88363256,  0.93943229,  0.17647813, -2.17098224, -0.55687232])

In [3]:
# Generate 10 random integers between 1 and 100 (inclusive)
random_integers = np.random.randint(1, 101, 10)
random_integers

array([97, 22, 26, 69, 64, 58,  7, 73, 83, 75])

In [8]:
# Create an array and shuffle its elements
arr = np.array([1, 2, 3, 4, 5])
shuffled_arr = np.random.permutation(arr)
shuffled_arr

array([4, 5, 2, 1, 3])

In [9]:
# Sample 5 elements randomly with replacement from an array
arr = np.array([1, 2, 3, 4, 5])
random_samples = np.random.choice(arr, 5, replace=True)
random_samples

array([1, 3, 5, 1, 1])

In [10]:
# Sample 3 elements randomly without replacement from an array
arr = np.array([1, 2, 3, 4, 5])
random_samples = np.random.choice(arr, 3, replace=False)
random_samples

array([3, 5, 1])