In [15]:
import numpy as np

# Sample NumPy array for demonstration
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [30]:
# 1. Basic Arithmetic Operations
addition = arr + 2  # Add a scalar to all elements
print(addition)
subtraction = arr - 2  # Subtract a scalar from all elements
print(subtraction)
multiplication = arr * 2  # Multiply all elements by a scalar
print(multiplication)
division = arr / 2  # Divide all elements by a scalar
print(division)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [17]:
# 2. Element-wise Mathematical Functions
square = np.square(arr)  # Square each element
sqrt = np.sqrt(arr)  # Square root of each element
exp = np.exp(arr)  # Exponential of each element
log = np.log(arr)  # Natural logarithm of each element

In [18]:
# 3. Trigonometric Functions
sin_arr = np.sin(arr)  # Sine of each element
cos_arr = np.cos(arr)  # Cosine of each element
tan_arr = np.tan(arr)  # Tangent of each element

In [19]:
# 4. Statistical Functions
mean_value = np.mean(arr)  # Mean (average) of elements
median_value = np.median(arr)  # Median of elements
std_deviation = np.std(arr)  # Standard deviation of elements

In [20]:
# 5. Rounding and Absolute Values
round_arr = np.round(arr, decimals=2)  # Round elements to specified decimals
abs_arr = np.abs(arr)  # Absolute values of elements

In [21]:
# 6. Element-wise Comparisons
greater_than_3 = arr > 3  # Boolean array indicating elements greater than 3
less_than_equal_to_2 = arr <= 2  # Boolean array indicating elements less than or equal to 2

In [22]:
# 7. Aggregation Functions
sum_elements = np.sum(arr)  # Sum of all elements
min_element = np.min(arr)  # Minimum element
max_element = np.max(arr)  # Maximum element

In [23]:
# 8. Element-wise Operations on Multiple Arrays
arr2 = np.array([2, 4, 6, 8, 10])
elementwise_multiply = arr * arr2  # Multiply corresponding elements of two arrays


In [24]:
# 9. Random Number Generation
random_numbers = np.random.rand(5)  # Generate 5 random numbers between 0 and 1

In [25]:
# 10. Sorting
sorted_arr = np.sort(arr)  # Sort elements in ascending order
argsort_arr = np.argsort(arr)  # Indices that would sort the array

In [26]:
# 11. Set Operations
unique_values = np.unique(arr)  # Unique elements in the array
intersection = np.intersect1d(arr, arr2)  # Intersection of two arrays
union = np.union1d(arr, arr2)  # Union of two arrays

In [28]:
# 12. Element-wise Power
power = np.power(arr, 3)  # Raise each element to the power of 3
power

array([  1,   8,  27,  64, 125], dtype=int32)