In [1]:
my_list = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
sorted_list = sorted(my_list)  # Sort the list in ascending order
print(sorted_list)  # Output: [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]

# If you want to sort in descending order:
sorted_list_desc = sorted(my_list, reverse=True)
print(sorted_list_desc)  # Output: [9, 6, 5, 5, 5, 4, 3, 3, 2, 1, 1]

# Note that sorted() does not modify the original list; it returns a new sorted list.


[1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]
[9, 6, 5, 5, 5, 4, 3, 3, 2, 1, 1]


In [2]:
import numpy as np

my_array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
my_array.sort()  # Sort the NumPy array in ascending order in-place
print(my_array)  # Output: [1 1 2 3 3 4 5 5 5 6 9]

# If you want to sort in descending order, you can reverse the array using slicing:
my_array_desc = my_array[::-1]
print(my_array_desc)  # Output: [9 6 5 5 5 4 3 3 2 1 1]

# Note that sort() modifies the original array in-place.


[1 1 2 3 3 4 5 5 5 6 9]
[9 6 5 5 5 4 3 3 2 1 1]


In [3]:
# Example 1: Sorting a list in ascending order using sorted()
my_list = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
sorted_list = sorted(my_list)  # Sort the list in ascending order
print(sorted_list)  # Output: [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]

[1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]


In [5]:
# Example 2: Sorting a list in descending order using sorted()
sorted_list_desc = sorted(my_list, reverse=True)
print(sorted_list_desc)  # Output: [9, 6, 5, 5, 5, 4, 3, 3, 2, 1, 1]

[9, 6, 5, 5, 5, 4, 3, 3, 2, 1, 1]


In [4]:
# Example 3: Sorting a NumPy array in ascending order using sort()
import numpy as np
my_array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
my_array.sort()  # Sort the NumPy array in ascending order in-place
print(my_array)  # Output: [1 1 2 3 3 4 5 5 5 6 9]

[1 1 2 3 3 4 5 5 5 6 9]


In [6]:
# Example 4: Sorting a NumPy array in descending order using sort()
my_array_desc = np.sort(my_array)[::-1]
print(my_array_desc)  # Output: [9 6 5 5 5 4 3 3 2 1 1]

[9 6 5 5 5 4 3 3 2 1 1]


In [7]:
# Example 5: Sorting a list of strings in alphabetical order
my_strings = ["apple", "banana", "cherry", "date", "elderberry"]
sorted_strings = sorted(my_strings)
print(sorted_strings)  # Output: ['apple', 'banana', 'cherry', 'date', 'elderberry']

['apple', 'banana', 'cherry', 'date', 'elderberry']


In [9]:
# Example 6: Sorting a NumPy array in ascending order along a specified axis
matrix = np.array([[3, 1, 2], [6, 5, 4], [9, 8, 7]])
sorted_matrix = np.sort(matrix, axis=0)  # Sort along columns (axis=0)
print(sorted_matrix)

[[3 1 2]
 [6 5 4]
 [9 8 7]]
