In [12]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

union_result = np.union1d(array1, array2)
# Resulting union_result: [1 2 3 4 5 6 7]
# we need to mention the dimension of array

union_result

array([1, 2, 3, 4, 5, 6, 7])

In [2]:

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

intersection_result = np.intersect1d(array1, array2)
# Resulting intersection_result: [3 4 5]

intersection_result

array([3, 4, 5])

In [3]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

difference_result = np.setdiff1d(array1, array2)
# Resulting difference_result: [1 2]

difference_result

array([1, 2])

In [4]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

symmetric_difference_result = np.setxor1d(array1, array2)
# Resulting symmetric_difference_result: [1 2 6 7]


symmetric_difference_result

array([1, 2, 6, 7])

In [5]:
array = np.array([3, 1, 2, 3, 4, 2, 5, 6, 6, 7])
unique_values = np.unique(array)
# Resulting unique_values: [1 2 3 4 5 6 7]

unique_values

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4])

is_subset = np.in1d(array2, array1)
# Resulting is_subset: [ True  True]

is_subset

array([ True,  True])

In [7]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4])

is_superset = np.in1d(array1, array2)
# Resulting is_superset: [False  True False  True False]
 
is_superset

array([False,  True, False,  True, False])

In [9]:
array = np.array([3, 1, 2, 3, 4, 2, 5, 6, 6, 7])
unique_values, unique_indices = np.unique(array, return_index=True)
# Resulting unique_values: [1 2 3 4 5 6 7]
# Resulting unique_indices: [1 2 0 4 6 7 8]

print(unique_values)
print(unique_indices)

[1 2 3 4 5 6 7]
[1 2 0 4 6 7 9]


In [10]:
# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Find the minimum and maximum values in the entire matrix
min_value = np.min(matrix)
max_value = np.max(matrix)

print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Minimum Value: 1
Maximum Value: 9


In [11]:
# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Find the minimum and maximum values along each row (axis=1)
min_values_row = np.min(matrix, axis=1)
max_values_row = np.max(matrix, axis=1)

# Find the minimum and maximum values along each column (axis=0)
min_values_column = np.min(matrix, axis=0)
max_values_column = np.max(matrix, axis=0)

print("Minimum Values Along Rows:", min_values_row)
print("Maximum Values Along Rows:", max_values_row)
print("Minimum Values Along Columns:", min_values_column)
print("Maximum Values Along Columns:", max_values_column)


Minimum Values Along Rows: [1 4 7]
Maximum Values Along Rows: [3 6 9]
Minimum Values Along Columns: [1 2 3]
Maximum Values Along Columns: [7 8 9]
